### ISSUE TITLE
[BUG] Encoundered Error During Side_Setup Event Phase

### ISSUE THREAD

**Issue by Versimno** [ReconCubed/thecommunityupdate#6]
**Describe the bug**
Upon launching the game, I am met with [this page](https://imgur.com/a/OHZx9gi).

**To Reproduce**
1. Install Minecraft 1.14.4, Forge 28.2.6, and The Community Update 1.14.4-0.1.4
2. Launch the game

**Expected behavior**
Successful launch

**Screenshots**
[https://imgur.com/a/OHZx9gi](https://imgur.com/a/OHZx9gi)

**Desktop (please complete the following information):**
 - Minecraft Version 1.14.4
 - The Community Update 1.14.4-0.1.4
 - Forge Version 28.2.6

**Additional context**
Latest.log [https://pastebin.com/yd9b5jWY](https://pastebin.com/yd9b5jWY)
Launched via the Twitch App

**Comment by the-inconvenience-store** [comment]
Try using the stable Forge versions, or Forge version 28.2.3. This mod was built on 28.2.3, and it looks like in 28.2.6 some deobfuscation (in particular, the skinMap field) hasn't been mapped yet. You shouldn't miss anything from the forge version downgrade, I personally run everything on 28.2.3!
